### ISSUE TITLE
Script Hook use

### ISSUE THREAD

**Issue by vaodaa** [qubard/Chrollo#1]
Can i use it on FiveM is still working ?

**Comment by qubard** [comment]
Yes it should work for months if not years. I just tested it right now. All Chrollo does is modify `lua_shared.dll` when it gets injected

**Comment by qubard** [comment]
When I closed this it wasn't working, but I just updated it and it works now. The address of the function that needs to be hooked changed so I made it scan for it using a signature scan and also updated the `server_name` pointer.
