### ISSUE TITLE
Chtollo doesn't bypass server's client lua disabling at all.

### ISSUE THREAD

**Issue by wweony23** [qubard/Chrollo#5]
Maybe I've done something wrong...
How could I fix it.
Hope creator will answer me instead of ignore.
https://youtu.be/KewOR_biOi4
I created custom map folder with russian letters (bec server named like it).

**Comment by qubard** [comment]
it's not supposed to do that. [you should use the script enforcer bypass for that](https://github.com/qubard/Script-Enforcer-Bypass)
